* async-play
  A clojurescript webapp to exercise core.async library by sending
  keyborad events to an input channel.

** Overview
   Use an event stream input channel to transform a source object to
   match a target object. Events can come from browser as well as from
   a browser connected repl.

** Usage
*** cljs
    lein cljsbuild once
    lein cljsbuild auto

*** clojure repl
    M-x cider-jack-in

*** browser repl
    > (in-ns 'async-play.web.play)
   > @vertices
   > (sigma)
   > (position :v1 square)


**** cljsbuile
    lein trampoline cljsbuild repl-listen
**** piggieback

   #+BEGIN_SRC clojure
  (do
    (require 'cljs.repl.browser)
    (cemerick.piggieback/cljs-repl
     :repl-env
     (doto (cljs.repl.browser/repl-env :port 9000)
       cljs.repl/-setup)))
    #+END_SRC

   
   https://github.com/cemerick/piggieback
   nREPL middleware that enables the bootstrap of a ClojureScript REPL
   on top of an nREPL session.
   [com.cemerick/piggieback "0.0.5"]

   (js/alert "I'm ready!")

   > (js/alert "Hello from a browser connected repl")

*** web server
   start simple server:
   $ cd resources/public
   $ python -m SimpleHTTPServer 8888

   http://localhost:8888/hello.html
   
** Resources
*** core.aync
    - https://github.com/clojure/core.async
    - https://github.com/swannodette/async-tests
    - http://dimagog.github.io/blog/clojure/clojurescript/2013/07/12/making-http-requests-from-clojurescript-with-core.async/
    - https://github.com/Dimagog/AsyncGET
    - http://tech.puredanger.com/2013/07/10/rps-core-async/
    - http://rigsomelight.com/2013/07/18/clojurescript-core-async-todos.html

*** cljs
    - https://github.com/magomimmo/modern-cljs/blob/master/doc/tutorial-02.md
    - https://groups.google.com/forum/#!topic/clojure/6H-hooiAW3I
    - http://himera.herokuapp.com/synonym.html
    - http://himera.herokuapp.com/index.html

*** canvas
    - http://developer.apple.com/library/safari/#documentation/AudioVideo/Conceptual/HTML-canvas-guide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40010542-CH1-SW1
    - http://www.html5canvastutorials.com/kineticjs/html5-canvas-kineticjs-regular-polygon-tutorial/
    - http://fabricjs.com/controls/
    - https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#rgba()
    - https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Canvas_tutorial/Basic_animations
    - https://github.com/learnboost/node-canvas
    
** License
   Copyright © 2013 Walter P Babic

   Distributed under the Eclipse Public License either version 1.0 or (at
   your option) any later version.

